### ISSUE TITLE
Apply our standard way of working with repos and tasks

### ISSUE THREAD

**Issue by buep** [Praqma/noops#1]
Do a waffle, apply labels in repo and milestones and stuff as described in the below blogs

http://www.praqma.com/stories/milestones-and-officehours/
http://www.praqma.com/stories/a-pragmatic-workflow/

* remove all existing labels (the github default labels)
* apply our set of labels
* create the two default milestones
* create waffle for the repo
* configure the waffle in our standard way (this means add a column, change description on a few columns and make the columns use our labels - see the JOSRA waffle for how it is configured)

**Comment by timea** [comment]
All setup is done.
