### ISSUE TITLE
Zabbix: Compose configuration and docs on how to start a Zabbix

### ISSUE THREAD

**Issue by buep** [Praqma/noops#13]
We plan that our Zabbix server is managed using docker-machine (pointing to our docker engine somewhere) and docker-compose to describe the solution.

Deliverables:

- document how to start our Zabbix monitoring solution
- create a docker-compose file that starts Zabbix and persist data across upgrades, stops and starts

_This issue is an elaboration on work needed for #2 _

**Comment by buep** [comment]
Example https://github.com/monitoringartist/zabbix-xxl/blob/master/Dockerfile/zabbix-2.4/docker-compose.yml

**Comment by buep** [comment]
> create a docker-compose file that starts Zabbix and persist data across upgrades, stops and starts

Is this full-filled? And what are the commands? I can only see the docker-compose file.

**Comment by timea** [comment]
Please take a look at both commit messages and the actual files. That is where I give the deliverables.

My commit message: Please see the documentation in the docker-compose.yml

The documentation in the yml file:
# Run docker-compose up from the same directory you put this file in
 +# It will create 3 containers - zabbix-db-storage, zabbix-db, zabbix-server
 +
 +# zabbix-db-storage is a persistent data store, keeping the data after the db stoppes
 +# zabbix-db is running the db as a service saving to zabbix-db-storage
 +# zabbix-server running the server
 +
 +# After about a minute the log seems to have stopped, you get the web UI of zabbix on localhost:80

**Comment by buep** [comment]
I read it all, but do it persist data across upgrades ? Did you try it? I was looking for the commands you used to upgrade, and try that.

Also I'm not sure about the persistence.... is the `volumes` in the compose file meaning local mount? 

Where is the volumes created when you use docker-machine to run the containers with compose on digital ocean?

**Comment by buep** [comment]
default password...

**Comment by buep** [comment]
okay, cant get it to work, so need exact commands and readme.

**Comment by timea** [comment]
Well, I reacted too fast, you are right. I tested only locally running the compose file. I will take a look at that one now.
