### ISSUE TITLE
Edit existing docker image to be automatically monitored by our Zabbix server

### ISSUE THREAD

**Issue by buep** [Praqma/noops#16]
Say I need to start a new docker container, it could be Gitlab-ce or one of our own containers. One that lives as a one of service for a longer time (it doesn't make sense to monitor temporary build containers for example).

How will I monitor such an container, so when we start it it will automatically connect to our Zabbix server and be monitored some standard way.

Goal:

* make the necessary changes to an existing Dockerfile
* make the necessary changes to our existing Zabbix docker setup

All changes must be persisted in git - so you can't edit anything in the UI on Zabbix-
I assume some kind of Zabbix configuration file needs to be written, adjusted and supplied to our Zabbix server when it is started from compose (or rather restarted).
I imagine I have to add something to the gitlab docker file.

**Comment by buep** [comment]
Making this a briefing, since it is being groomed to other issues. When done we close it.

Timebox the grooming please.

**Comment by timea** [comment]
Broken down to tasks
