### ISSUE TITLE
Switch to use our Praqma Digital Ocean account

### ISSUE THREAD

**Issue by buep** [Praqma/noops#19]
You have been invited.

**Comment by buep** [comment]
Remember to close your own :-)

**Comment by timea** [comment]
I use it for my bachelor project, so I will need it, but the note is
appreciated :)

**Comment by buep** [comment]
> I use it for my bachelor project, so I will need it, but the note is appreciated :)

I meant your Praqma droplet, not your DO account. You need your account to work in the Praqma org on DO.

:-)

**Comment by timea** [comment]
Haha, okay :)
