### ISSUE TITLE
Usable, extendable Zabbix Docker image

### ISSUE THREAD

**Issue by timea** [Praqma/noops#2]
We are planning to run a test of 2 monitoring server solutions, Zabbix is one of them. 

**Product:** 
Docker image of a monitoring server

**Requirements:**
- Generic
We want an image that can be used by anyone with the need of monitoring servers in a simple manner, be it whatever OS or setup

- Extendible
It needs to be extendible in the sense that we need to be able create some new functionality, visualizing or check scripts run on the monitored nodes or similar as they come up in the process.

**Approach**
Exisiting docker files should be observed and see if they are usable starting point otherwise build the image bottom up.

2 jobs (per image) needs to be set up in Jenkins.
Job 1) picking up the respective Dockerfile from this repo and building a Docker image, triggered manually.
Job 2) picking up the Docker image created by Job 1) and deploying it to our docker hub.

**Comment by buep** [comment]
The last part of this briefing related to release job is found in #12

**Comment by buep** [comment]
According to #4 there is no more issues to be created to cover this briefing to closing.
