### ISSUE TITLE
Research on rolling it into production

### ISSUE THREAD

**Issue by buep** [Praqma/noops#20]
See the limitations section in servermonitoring/zabbix-digital-ocean-documentation.md where some challenges of rolling this into production is mentioned.

How would we roll this in production, so a group of us can maintain it and have access to it?

Timeboxed research - write up in subsection to the limitation section is the goal.

**Comment by buep** [comment]
Solution might be to share one machine to control the containers from, or maybe shipyard.

**Comment by buep** [comment]
Time is up, remember it is a timebox:-)

**Comment by timea** [comment]
Time is not up yet, this was not the only thing I did. Still have an hour
about :) Will report at the end :)

**Comment by buep** [comment]
I created a two new issues based on your findings.
