### ISSUE TITLE
Handling secrect - research best practices

### ISSUE THREAD

**Issue by timea** [Praqma/noops#23]
This is a subtask of #22.

Timeboxed research resulting in a report about best practices in regards to _keys, passwords, API tokens etc. stored somewhere securely, but also in way that works with automation so we run deployments from our management machine or deployment automation the secrets are used and available._

**Comment by buep** [comment]
Skip the writing, I prefer a picture instead.

Look at the Vault project.

Tip: Consider you always have to have a key somewhere, so running automation for example from Jenkins you need to have a secret in the job.
If you use command line, you would need the secret in an environment variable instead, but maybe populate from Vault. 
Either how, you need to have something, to avoid other to re-use our setup.

**Comment by buep** [comment]
This is a small issue and have been in progress 4 days?

**Comment by timea** [comment]
This was almost done missing the picture we talked about yesterday. I will
get back to it. When I had a question or made a PR, I kept the issue in
progress to see what I need to finish up next time. It is not
representative of how much time is spent on it continuously. :) I will get
back to it today.
