### ISSUE TITLE
Dockerimage edit - see if the Agent XXL is interesting for us

### ISSUE THREAD

**Issue by timea** [Praqma/noops#26]
This is a subtask of #16 .

After understanding all the steps of a setup, evaluate if the existing [Agent XXL image](https://hub.docker.com/r/monitoringartist/zabbix-agent-xxl-limited/) is interesting in any aspect.

The delivery is a short summary of the findings.

**Comment by buep** [comment]
Agent XXX image is to monitor docker hosts, that is not really part of what I want in #16.
So skipping this issue.

**Comment by timea** [comment]
Would you like to close it then?

**Comment by buep** [comment]
Not for now
