### ISSUE TITLE
Use pretested to merge ready branches

### ISSUE THREAD

**Issue by timea** [Praqma/noops#31]
Create the jenkins job in job dsl, add it to our job dsl repo and run it on the server.
Link to job in the repo root readme and explain it serves as integration job and we work using our pragmatic work flow.

**Comment by buep** [comment]
Also remember to link to job in the repo root readme and explain it serves as integration job and we work using our pragmatic work flow.

**Comment by timea** [comment]
Updated the task with your comment.

**Comment by timea** [comment]
was just testing the job not finished yet

**Comment by buep** [comment]
can't find the job our server?

**Comment by buep** [comment]
sorry, not logged in...

maybe a link in the readme to the actual job... anyway, good we got the flow automated

**Comment by timea** [comment]
noops-seed and noops-pretested. I can put it in the file.

**Comment by timea** [comment]
I did not want to add a link as that will be broken when you are not logged in. But I put the name in the description.
