### ISSUE TITLE
Research can DO change the public IP

### ISSUE THREAD

**Issue by timea** [Praqma/noops#35]
This  is a potential danger we need to mitigate if we decide to use DO and they do not guarantee the public IP to be the same as all our agents could potentially try to report to a server on another IP.

**Comment by buep** [comment]
We solved this today:

* private IP can be reached from internet, but all droplets in the same data center can access it, thus other customers can try to take over our droplet.
* public ips can be removed in the droplet itself, eg. just removing eth0 on linux (if eth1 is private one)

So we can remove the public ip, but still not really private.

Spend the estimate talking to our colleagues about how we can secure a private cloud and make it access internal resource.

E.g. close it down in complete private zone, then connect it with P2P tunnelling over VPN ?

Delivery is just slacking about the problem, and figure out our next step.

**Comment by timea** [comment]
Awaiting feedback from colleagues on slack.

**Comment by timea** [comment]
As a delivery I posted to our operations slack channel the contents of this file committed. As the issue addresses 2 questions, I decided to create a file for it too in the repo. (Slack is not persisting data.)
